### ISSUE TITLE
В минорном релизе сломали обратную совместимость

### ISSUE THREAD

**Issue by neprja** [Tinkoff/invest-api-go-sdk#10]
Переименовали `investgo.MDStream` в `investgo.MarketDataStream` в _минорном_ блин релизе)

**Comment by jstalex** [comment]
Здравствуйте! В версии 1.4.2 проблему исправили

**Comment by neprja** [comment]
@jstalex Спасибо) Только тег поправьте ещё, там опять лишняя точка)
